from . import project_project_stage
from . import project_project
from . import project_task
from . import sale_order_line
from . import sale_order
from . import res_partner
from . import hr_employee
from . import analytic_line
from . import hr_leave_type
from . import provisional_timesheet_line
from . import hr_leave